# play 1
- name: Installing dependencies (like docker, awscli)
  hosts: all
  become: true
  gather_facts: false
  roles:
    - { role: dependencies}
# play 2
- name: Pull/prepare docker images
  hosts: all
  become: true
  roles:
    - { role: docker-images}
# play 3
- name: Configure files
  hosts: all
  become: true
  roles:
    - { role: artifacts}

- name: launch the stack
  hosts: all
  become: true
  roles:
    - { role: create-stack}
# play 5
- name: init data
  hosts: all
  become: true
  roles:
    - { role: initdata}
        